import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeft, Eye, EyeOff } from 'lucide-react'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { Brand } from '../components/Brand'
import { useAuth } from '../hooks/useAuth'
import { authSchema } from '../schemas/project'

type Values = z.infer<typeof authSchema>
export function AuthPage({ mode }: { mode: 'login' | 'signup' }) {
  const { user, signIn, signUp, demoMode } = useAuth(); const navigate = useNavigate(); const [show, setShow] = useState(false); const [serverError, setServerError] = useState(''); const [notice, setNotice] = useState('')
  const schema = mode === 'signup' ? authSchema.extend({ fullName: z.string().trim().min(2, 'Indiquez votre nom') }) : authSchema
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { email: demoMode ? 'demo@publia.app' : '', password: demoMode ? 'demopublia' : '', fullName: '' } })
  if (user) return <Navigate to="/dashboard" replace />
  const submit = async (values: Values) => { try { setServerError(''); if (mode === 'login') await signIn(values.email, values.password); else { const result = await signUp(values.fullName ?? '', values.email, values.password); if (result.needsConfirmation) { setNotice('Compte créé. Consultez votre boîte email pour confirmer votre inscription.'); return } } navigate('/dashboard') } catch (error) { setServerError(error instanceof Error ? error.message : 'Une erreur est survenue.') } }
  return <main className="grid min-h-screen bg-white lg:grid-cols-2"><div className="flex min-h-screen flex-col p-6 sm:p-10"><div className="flex justify-between"><Brand/><Link to="/" className="flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/>Accueil</Link></div><div className="mx-auto my-auto w-full max-w-md py-12"><span className="eyebrow">{mode === 'login' ? 'Heureux de vous revoir' : 'Votre vitrine en quelques minutes'}</span><h1 className="mt-5 text-4xl font-bold tracking-tight">{mode === 'login' ? 'Connectez-vous à Publia' : 'Créez votre compte Publia'}</h1><p className="mt-3 text-slate-500">{mode === 'login' ? 'Retrouvez vos projets et leurs statistiques.' : 'Commencez gratuitement, sans carte bancaire.'}</p>{demoMode && <p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Mode démo actif : utilisez les identifiants préremplis ou n’importe quelles valeurs valides.</p>}
      <form onSubmit={handleSubmit(submit)} className="mt-8 grid gap-5">{mode === 'signup' && <label className="field"><span>Nom complet</span><input {...register('fullName')} autoComplete="name" placeholder="Aminata Diallo" />{errors.fullName && <small>{errors.fullName.message}</small>}</label>}<label className="field"><span>Adresse email</span><input {...register('email')} type="email" autoComplete="email" placeholder="vous@exemple.com"/>{errors.email && <small>{errors.email.message}</small>}</label><label className="field"><span className="flex justify-between">Mot de passe {mode === 'login' && <Link to="/mot-de-passe-oublie" className="text-brand-700">Mot de passe oublié ?</Link>}</span><span className="relative"><input {...register('password')} type={show ? 'text' : 'password'} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} placeholder="8 caractères minimum" className="w-full pr-11"/><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" aria-label="Afficher le mot de passe">{show ? <EyeOff className="h-5 w-5"/> : <Eye className="h-5 w-5"/>}</button></span>{errors.password && <small>{errors.password.message}</small>}</label>{serverError && <p className="error-box">{serverError}</p>}{notice && <p className="success-box">{notice}</p>}<button disabled={isSubmitting} className="btn-primary btn-large">{isSubmitting ? 'Un instant…' : mode === 'login' ? 'Se connecter' : 'Créer mon compte'}</button></form><p className="mt-7 text-center text-sm text-slate-500">{mode === 'login' ? 'Nouveau sur Publia ?' : 'Vous avez déjà un compte ?'} <Link className="font-semibold text-brand-700" to={mode === 'login' ? '/inscription' : '/connexion'}>{mode === 'login' ? 'Créer un compte' : 'Se connecter'}</Link></p></div></div><div className="relative hidden overflow-hidden bg-ink p-14 text-white lg:flex lg:flex-col lg:justify-end"><div className="absolute inset-0 auth-pattern opacity-20"/><div className="relative max-w-lg"><p className="text-3xl font-semibold leading-snug">« Une bonne idée mérite une adresse que l’on a envie de partager. »</p><p className="mt-5 text-sm text-slate-400">Publia — La vitrine simple de vos projets numériques</p></div></div></main>
}