import { ArrowRight, BadgeCheck, BarChart3, BookOpen, BriefcaseBusiness, Building2, Check, Copy, GraduationCap, HeartHandshake, Link2, Palette, QrCode, Rocket, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect } from 'react'
import { Brand } from '../components/Brand'

const steps = [
  { icon: Link2, n: '01', title: 'Collez votre lien', text: 'Ajoutez l’adresse GitHub Pages ou le lien de votre application déjà publiée.' },
  { icon: Palette, n: '02', title: 'Soignez la présentation', text: 'Ajoutez votre logo, une image, vos couleurs et les informations essentielles.' },
  { icon: Rocket, n: '03', title: 'Partagez partout', text: 'Diffusez une adresse simple, un QR code ou partagez directement sur vos réseaux.' }
]
const audiences = [{ icon: GraduationCap, label: 'Étudiants' }, { icon: BriefcaseBusiness, label: 'Consultants' }, { icon: HeartHandshake, label: 'ONG' }, { icon: BookOpen, label: 'Chercheurs' }, { icon: Building2, label: 'Entrepreneurs' }]

export function HomePage() {
  useEffect(() => {
    const scrollToHash = () => {
      const id = decodeURIComponent(window.location.hash.slice(1))
      if (!id) return
      window.requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }))
    }
    scrollToHash()
    window.addEventListener('hashchange', scrollToHash)
    return () => window.removeEventListener('hashchange', scrollToHash)
  }, [])
  return <>
    <section className="relative overflow-hidden bg-white"><div className="hero-grid absolute inset-0 opacity-50" /><div className="container relative grid min-h-[720px] items-center gap-14 py-20 lg:grid-cols-[1.05fr_.95fr]">
      <div><span className="eyebrow"><Sparkles className="h-4 w-4" />Pensé pour les créateurs qui veulent aller vite</span><h1 className="mt-6 max-w-3xl text-5xl font-bold leading-[1.06] tracking-[-.04em] text-ink sm:text-6xl lg:text-7xl">Publiez et partagez votre application <span className="text-brand-600">en quelques minutes.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">Transformez un lien technique en une page professionnelle, claire et facile à partager — sans maîtriser l’hébergement web.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/inscription" className="btn-primary btn-large">Publier mon application<ArrowRight className="h-5 w-5" /></Link><Link to="/p/afridata-ready" className="btn-secondary btn-large">Voir un exemple</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-500"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-brand-600" />Aucune carte bancaire</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-brand-600" />Prêt en 3 étapes</span></div></div>
      <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-8 rounded-full bg-brand-100/50 blur-3xl" /><div className="relative rotate-1 rounded-[2rem] border border-slate-200 bg-white p-3 shadow-[0_40px_100px_-35px_rgba(15,118,110,.45)]"><div className="flex items-center gap-2 border-b px-3 py-3"><span className="h-2.5 w-2.5 rounded-full bg-red-300"/><span className="h-2.5 w-2.5 rounded-full bg-amber-300"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-300"/><div className="mx-auto rounded-md bg-slate-100 px-10 py-1 text-[10px] text-slate-400">publia.app/p/afridata</div></div><div className="overflow-hidden rounded-2xl bg-slate-50"><div className="h-44 bg-gradient-to-br from-brand-900 via-brand-700 to-teal-400 p-8 text-white"><span className="rounded-lg bg-white/15 px-3 py-1 text-xs">Données & recherche</span><p className="mt-12 text-3xl font-bold">AfriData Ready</p></div><div className="p-7"><p className="text-sm leading-6 text-slate-600">Des données africaines fiables, accessibles et prêtes à éclairer vos décisions.</p><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-brand-700 py-3 text-sm font-semibold text-white">Ouvrir l’application <ArrowRight className="h-4 w-4" /></button><div className="mt-5 grid grid-cols-3 gap-3 text-center text-xs text-slate-500"><span className="rounded-lg bg-white p-3"><QrCode className="mx-auto mb-1 h-4 w-4" />QR code</span><span className="rounded-lg bg-white p-3"><Copy className="mx-auto mb-1 h-4 w-4" />Copier</span><span className="rounded-lg bg-white p-3"><BarChart3 className="mx-auto mb-1 h-4 w-4" />128 vues</span></div></div></div></div></div>
    </div></section>
    <section id="fonctionnement" className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Simple par conception</span><h2>Du lien brut à la page pro, sans complication.</h2><p>Publia vous guide à chaque étape. Vous gardez votre site actuel et améliorez simplement sa présentation.</p></div><div className="mt-14 grid gap-6 md:grid-cols-3">{steps.map(({ icon: Icon, n, title, text }) => <article key={n} className="card relative"><span className="absolute right-6 top-5 text-4xl font-black text-slate-100">{n}</span><div className="icon-box"><Icon /></div><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section id="avantages" className="section bg-ink text-white"><div className="container grid items-center gap-14 lg:grid-cols-2"><div><span className="eyebrow border-white/10 bg-white/10 text-teal-200">Votre projet mérite mieux qu’un lien brut</span><h2 className="mt-6 text-4xl font-bold tracking-tight sm:text-5xl">Une présence crédible, partout où vous la partagez.</h2><p className="mt-6 text-lg leading-8 text-slate-300">Présentez votre travail avec le même soin que vous avez mis à le construire. Publia rassemble l’essentiel sur une page rapide, lisible et adaptée au mobile.</p><Link to="/inscription" className="mt-8 inline-flex items-center gap-2 font-semibold text-teal-300">Créer ma page <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-4 sm:grid-cols-2">{[[BadgeCheck,'Une image professionnelle','Une page cohérente qui inspire confiance dès le premier regard.'],[QrCode,'Partage sans friction','Lien, QR code, WhatsApp et LinkedIn à portée de clic.'],[BarChart3,'Visites visibles','Suivez simplement l’intérêt généré par chaque projet.'],[ShieldCheck,'Données protégées','Vos projets sont isolés grâce aux politiques de sécurité Supabase.']].map(([I,t,d]) => { const Icon=I as typeof BadgeCheck; return <article key={String(t)} className="rounded-2xl border border-white/10 bg-white/5 p-6"><Icon className="h-6 w-6 text-teal-300"/><h3 className="mt-4 font-semibold">{String(t)}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{String(d)}</p></article>})}</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow"><Users className="h-4 w-4" />Pour celles et ceux qui construisent</span><h2>Votre travail est utile. Rendez-le visible.</h2><p>Portfolio, outil de terrain, tableau de bord, mémoire interactif ou produit SaaS : Publia donne un écrin simple à chaque projet.</p></div><div className="mt-12 flex flex-wrap justify-center gap-3">{audiences.map(({icon: Icon,label}) => <span key={label} className="flex items-center gap-2 rounded-full border bg-white px-5 py-3 font-medium shadow-sm"><Icon className="h-5 w-5 text-brand-600"/>{label}</span>)}</div><div className="mt-16 rounded-[2rem] bg-brand-50 px-6 py-12 text-center sm:px-12"><h2 className="text-3xl font-bold sm:text-4xl">Prêt à mieux présenter votre application ?</h2><p className="mx-auto mt-4 max-w-xl text-slate-600">Créez gratuitement votre première page Publia et partagez-la aujourd’hui.</p><Link to="/inscription" className="btn-primary btn-large mt-7">Commencer maintenant<ArrowRight className="h-5 w-5"/></Link></div></div></section>
    <footer className="border-t bg-white"><div className="container flex flex-col items-center justify-between gap-5 py-8 sm:flex-row"><Brand/><p className="text-sm text-slate-500">© {new Date().getFullYear()} Publia. Fait pour donner de l’élan à vos idées.</p></div></footer>
  </>
}

