import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeft, Check, ExternalLink, Save } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Loading } from '../components/Loading'
import { useAuth } from '../hooks/useAuth'
import { projectSchema, slugify, type ProjectFormValues } from '../schemas/project'
import { projectService } from '../services/projects'
import { publicProjectUrl } from '../lib/utils'

const categories=['Éducation','Données & recherche','Entreprise','Impact social','Productivité','Portfolio','Santé','Autre']
const defaults:ProjectFormValues={name:'',slug:'',source_url:'',short_description:'',long_description:'',logo_url:'',cover_url:'',category:'',creator_name:'',contact_email:'',linkedin_url:'',github_url:'',primary_color:'#0f766e',is_public:true,is_active:true}
export function ProjectFormPage(){
  const {id}=useParams();const editing=Boolean(id);const {user}=useAuth();const navigate=useNavigate();const [loading,setLoading]=useState(editing);const [serverError,setServerError]=useState('');const slugTouched=useRef(editing)
  const {register,handleSubmit,watch,setValue,reset,setError,formState:{errors,isSubmitting}}=useForm<ProjectFormValues>({resolver:zodResolver(projectSchema),defaultValues:defaults})
  const name=watch('name');const slug=watch('slug');const color=watch('primary_color')
  useEffect(()=>{if(!slugTouched.current)setValue('slug',slugify(name),{shouldValidate:Boolean(name)})},[name,setValue])
  useEffect(()=>{if(!id)return;projectService.get(id).then(p=>{if(!p){setServerError('Projet introuvable.');return}reset({...p,long_description:p.long_description??'',logo_url:p.logo_url??'',cover_url:p.cover_url??'',contact_email:p.contact_email??'',linkedin_url:p.linkedin_url??'',github_url:p.github_url??''})}).catch(()=>setServerError('Impossible de charger le projet.')).finally(()=>setLoading(false))},[id,reset])
  const submit=async(values:ProjectFormValues)=>{if(!user)return;setServerError('');try{if(await projectService.slugExists(values.slug,id)){setError('slug',{message:'Ce slug est déjà utilisé. Essayez une variante.'});return}if(id)await projectService.update(id,values);else await projectService.create(user.id,values);navigate('/dashboard')}catch(e){setServerError(e instanceof Error?e.message:'Impossible d’enregistrer le projet.')}}
  if(loading)return <Loading label="Chargement du projet…"/>
  const field=(name:keyof ProjectFormValues,label:string,placeholder='',type='text')=><label className="field"><span>{label}</span><input {...register(name)} type={type} placeholder={placeholder}/>{errors[name]&&<small>{String(errors[name]?.message)}</small>}</label>
  return <div className="p-5 sm:p-8 lg:p-10"><form onSubmit={handleSubmit(submit)} className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><Link to="/dashboard" className="mb-4 flex items-center gap-2 text-sm text-slate-500 hover:text-brand-700"><ArrowLeft className="h-4 w-4"/>Retour aux projets</Link><h1 className="text-3xl font-bold">{editing?'Modifier le projet':'Créer une nouvelle vitrine'}</h1><p className="mt-2 text-slate-500">Les champs marqués d’un astérisque sont obligatoires.</p></div><button className="btn-primary btn-large" disabled={isSubmitting}><Save className="h-5 w-5"/>{isSubmitting?'Enregistrement…':'Enregistrer'}</button></div>{serverError&&<p className="error-box mt-6">{serverError}</p>}
    <div className="mt-8 grid items-start gap-6 lg:grid-cols-[1fr_320px]"><div className="grid gap-6"><section className="form-section"><h2>Informations essentielles</h2><p>Ce que les visiteurs verront en premier.</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{field('name','Nom du projet *','Ex. AfriData Ready')}<label className="field"><span>Nom personnalisé du lien *</span><input {...register('slug',{onChange:()=>{slugTouched.current=true}})} placeholder="afridata-ready"/><small>Modifiez ce nom pour obtenir l’adresse que vous souhaitez partager.</small>{errors.slug&&<small>{errors.slug.message}</small>}</label><div className="sm:col-span-2 rounded-xl border border-brand-100 bg-brand-50 px-4 py-3 text-sm"><span className="text-slate-500">Votre lien public : </span><strong className="break-all text-brand-800">{publicProjectUrl(slug||'votre-projet')}</strong></div><div className="sm:col-span-2">{field('source_url','Lien du site d’origine *','https://…','url')}</div><label className="field sm:col-span-2"><span>Description courte *</span><textarea {...register('short_description')} rows={3} placeholder="Résumez la valeur de votre projet en une phrase."/><span className="flex justify-between"><small>{errors.short_description?.message}</small><em>{watch('short_description').length}/180</em></span></label><label className="field sm:col-span-2"><span>Description détaillée</span><textarea {...register('long_description')} rows={7} placeholder="Contexte, public, fonctionnalités principales…"/>{errors.long_description&&<small>{errors.long_description.message}</small>}</label></div></section>
      <section className="form-section"><h2>Identité visuelle</h2><p>Des liens vers des images publiques sont acceptés.</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{field('logo_url','URL du logo','https://…','url')}{field('cover_url','URL de la couverture','https://…','url')}<label className="field"><span>Couleur principale</span><span className="flex gap-2"><input {...register('primary_color')} type="color" className="h-11 w-14 cursor-pointer p-1"/><input {...register('primary_color')} className="flex-1"/></span>{errors.primary_color&&<small>{errors.primary_color.message}</small>}</label><label className="field"><span>Catégorie *</span><select {...register('category')}><option value="">Sélectionnez</option>{categories.map(c=><option key={c}>{c}</option>)}</select>{errors.category&&<small>{errors.category.message}</small>}</label></div></section>
      <section className="form-section"><h2>Créateur et contact</h2><p>Aidez les visiteurs à identifier et contacter le porteur du projet.</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{field('creator_name','Créateur ou organisation *','Nom ou organisation')}{field('contact_email','Email de contact','contact@exemple.com','email')}{field('linkedin_url','Lien LinkedIn','https://linkedin.com/in/…','url')}{field('github_url','Lien GitHub','https://github.com/…','url')}</div></section></div>
      <aside className="grid gap-6 lg:sticky lg:top-24"><section className="form-section"><h2>Publication</h2><div className="mt-5 grid gap-4"><label className="toggle-row"><span><strong>Page publique</strong><small>Visible par toute personne ayant le lien.</small></span><input type="checkbox" {...register('is_public')}/></label><label className="toggle-row"><span><strong>Projet actif</strong><small>Autorise l’accès à la page publique.</small></span><input type="checkbox" {...register('is_active')}/></label></div></section><section className="overflow-hidden rounded-2xl border bg-white"><div className="h-24 p-5 text-white" style={{background:`linear-gradient(135deg,${color},#17211f)`}}><p className="text-lg font-bold">{name||'Votre projet'}</p></div><div className="p-5"><p className="line-clamp-3 text-sm text-slate-500">{watch('short_description')||'Votre description apparaîtra ici.'}</p><span className="mt-4 flex items-center justify-center gap-2 rounded-lg py-2 text-sm font-semibold text-white" style={{backgroundColor:color}}>Ouvrir l’application <ExternalLink className="h-4 w-4"/></span><p className="mt-3 flex items-center gap-2 text-xs text-slate-400"><Check className="h-3 w-3 text-brand-600"/>Aperçu mis à jour en direct</p></div></section></aside></div></form></div>
}

