import { ArrowLeft, Copy, ExternalLink, Eye, Github, Linkedin, Mail, MessageCircle, Share2 } from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'
import { useEffect, useRef, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Brand } from '../components/Brand'
import { Loading } from '../components/Loading'
import { Toast } from '../components/Toast'
import { copyText, publicProjectUrl } from '../lib/utils'
import { projectService } from '../services/projects'
import type { Project } from '../types'

export function PublicProjectPage(){
  const {slug}=useParams();const [project,setProject]=useState<Project|null>(null);const [loading,setLoading]=useState(true);const [toast,setToast]=useState('');const recorded=useRef(false)
  useEffect(()=>{if(!slug)return;projectService.getPublic(slug).then(async p=>{setProject(p);if(p&&!recorded.current){recorded.current=true;await projectService.recordView(p.id);setProject(v=>v?{...v,views_count:(v.views_count??0)+1}:v)}}).finally(()=>setLoading(false))},[slug])
  if(loading)return <Loading label="Ouverture de la page…"/>
  if(!project)return <main className="grid min-h-screen place-items-center bg-slate-50 p-6 text-center"><div><div className="mx-auto mb-6"><Brand/></div><p className="text-7xl font-black text-brand-100">404</p><h1 className="mt-4 text-3xl font-bold">Cette page n’est pas disponible</h1><p className="mt-3 text-slate-500">Le projet est introuvable, privé ou temporairement désactivé.</p><Link to="/" className="btn-primary mt-7"><ArrowLeft className="h-4 w-4"/>Retour à l’accueil</Link></div></main>
  const url=publicProjectUrl(project.slug);const title=encodeURIComponent(`Découvrez ${project.name}`);const encoded=encodeURIComponent(url)
  const copy=async()=>{await copyText(url);setToast('Lien copié. Prêt à être partagé !')};const nativeShare=async()=>{if(navigator.share)await navigator.share({title:project.name,text:project.short_description,url});else await copy()}
  return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="container flex h-18 items-center justify-between"><Brand/><Link to="/" className="text-sm font-medium text-slate-500 hover:text-brand-700">Créer ma page</Link></div></header><main><div className="relative h-64 overflow-hidden bg-ink sm:h-80">{project.cover_url&&<img src={project.cover_url} alt={`Couverture de ${project.name}`} className="h-full w-full object-cover opacity-70"/>}<div className="absolute inset-0 bg-gradient-to-t from-ink/70 to-transparent"/></div><div className="container relative -mt-20 pb-16"><article className="overflow-hidden rounded-3xl border bg-white shadow-soft"><div className="grid lg:grid-cols-[1fr_340px]"><section className="p-6 sm:p-10 lg:p-12"><div className="flex flex-col items-start gap-5 sm:flex-row sm:items-center">{project.logo_url?<img src={project.logo_url} alt={`Logo de ${project.name}`} className="h-20 w-20 rounded-2xl border bg-white object-cover shadow-sm"/>:<div className="grid h-20 w-20 place-items-center rounded-2xl text-3xl font-bold text-white shadow-sm" style={{backgroundColor:project.primary_color}}>{project.name[0]}</div>}<div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{project.category}</span><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{project.name}</h1><p className="mt-1 text-sm text-slate-500">Par {project.creator_name}</p></div></div><p className="mt-8 text-xl font-medium leading-8 text-slate-700">{project.short_description}</p>{project.long_description&&<div className="mt-7 whitespace-pre-line border-t pt-7 leading-8 text-slate-600">{project.long_description}</div>}<a href={project.source_url} target="_blank" rel="noopener noreferrer" className="btn-large mt-9 inline-flex w-full items-center justify-center gap-2 rounded-xl font-semibold text-white sm:w-auto" style={{backgroundColor:project.primary_color}}>Ouvrir l’application<ExternalLink className="h-5 w-5"/></a><div className="mt-8 flex flex-wrap gap-3 border-t pt-7">{project.linkedin_url&&<a className="social-link" href={project.linkedin_url} target="_blank" rel="noopener noreferrer"><Linkedin/>LinkedIn</a>}{project.github_url&&<a className="social-link" href={project.github_url} target="_blank" rel="noopener noreferrer"><Github/>GitHub</a>}{project.contact_email&&<a className="social-link" href={`mailto:${project.contact_email}`}><Mail/>Contacter</a>}</div></section>
      <aside className="border-t bg-slate-50 p-6 sm:p-8 lg:border-l lg:border-t-0"><h2 className="font-semibold">Partager ce projet</h2><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>void copy()} className="share-button"><Copy/>Copier</button><button onClick={()=>void nativeShare()} className="share-button"><Share2/>Partager</button><a href={`https://wa.me/?text=${title}%20${encoded}`} target="_blank" rel="noopener noreferrer" className="share-button"><MessageCircle/>WhatsApp</a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encoded}`} target="_blank" rel="noopener noreferrer" className="share-button"><Linkedin/>LinkedIn</a></div><div className="mt-7 rounded-2xl border bg-white p-5 text-center"><QRCodeSVG value={url} size={174} level="M" marginSize={1} fgColor={project.primary_color} className="mx-auto max-w-full"/><p className="mt-3 text-xs text-slate-500">Scannez pour ouvrir cette page</p></div><div className="mt-6 flex items-center justify-center gap-2 text-sm text-slate-500"><Eye className="h-4 w-4"/><strong className="text-ink">{project.views_count??0}</strong> visites</div></aside></div></article><div className="mt-6 flex justify-center"><Link to="/" className="flex items-center gap-2 text-sm text-slate-500">Propulsé par <span className="font-bold text-brand-700">Publia</span></Link></div></div></main>{toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</div>
}